
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


import { DataUserContextProvider } from "./Context/nameUserContext";
import { ApiDataProvider } from "./Context/apiContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DataUserContextProvider >
     <ApiDataProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          
        </body>
      </html>
      </ApiDataProvider> 
    </DataUserContextProvider>
    
  );
}
