import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./Componets/Navbar";
import { DataUserContext } from "./Context/nameUserContext";
import { DataUserContextProvider } from "./Context/nameUserContext";
import FormLogin from "./formlogin/iniciar/page";
import Dashboard from "./Dashboard-Component/Dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DataUserContextProvider >
      <html lang="en">
        <body className={inter.className}>
          {children}
          
        </body>
      </html>
    </DataUserContextProvider>
  );
}
